FROM node:18 as builder

RUN apt-get update && apt-get install -y openssl

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install
COPY . .

RUN yarn prisma:generate

RUN yarn build

EXPOSE 3001